
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENORIGUAL = 11;
  public static final int AND = 5;
  public static final int ATRIBUICAO = 7;
  public static final int WHERE = 4;
  public static final int NAOIGUAL = 12;
  public static final int MAIORIGUAL = 10;
  public static final int MENORQUE = 9;
  public static final int STRING = 15;
  public static final int EOF = 0;
  public static final int NUMERO = 16;
  public static final int VIRGULA = 6;
  public static final int MAIORQUE = 8;
  public static final int ID = 14;
  public static final int error = 1;
  public static final int SELECT = 3;
  public static final int FROM = 2;
  public static final int TODOS = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FROM",
  "SELECT",
  "WHERE",
  "AND",
  "VIRGULA",
  "ATRIBUICAO",
  "MAIORQUE",
  "MENORQUE",
  "MAIORIGUAL",
  "MENORIGUAL",
  "NAOIGUAL",
  "TODOS",
  "ID",
  "STRING",
  "NUMERO"
  };
}

